# Instead of using TAB for indentation, use two spaces at the place of one TAB

# Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

# Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5]

# Controller to control end effector joints
hand_ee_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_6]
     
gazebo_ros_control:
    pid_gains:
      joint_1:
        p: 1.0
        i: 0.1
        d: 0.01
      joint_2:
        p: 1.0
        i: 0.1
        d: 0.01
      joint_3:
        p: 1.0
        i: 0.1
        d: 0.01
      joint_4:
        p: 1.0
        i: 0.1
        d: 0.01
      joint_5:
        p: 1.0
        i: 0.1
        d: 0.01
      joint_6:
        p: 1.0
        i: 0.1
        d: 0.01

